name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/front:v0.1 .

  deploy-docker-hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secerets.DOCKERHUB_USERNAME }}
          password: ${{ secerets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v2

      - name: Pushing image on DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/front:v0.1